# see https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Really Hard TODO app
Resources:

  TodoCommand:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/TodoCommand.zip
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 15
      Events:
        Post:
          Type: 'Api'
          Properties:
            Path: '/todo'
            Method: 'post'
      Environment:
        Variables:
          EventsTable: !Ref EventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable

  TodoSearch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/TodoSearch.zip
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 15
      Events:
        Search:
          Type: 'Api'
          Properties:
            Path: '/todo'
            Method: 'get'
        Get:
          Type: 'Api'
          Properties:
            Path: '/todo/{id}'
            Method: 'get'
      Environment:
        Variables:
          ElasticsearchDomainEndpoint: !GetAtt ElasticsearchDomain.DomainEndpoint
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - es:DescribeElasticsearchDomain
                - es:ESHttpHead
                - es:ESHttpGet
              Resource: !Join
                - ''
                - - !GetAtt ElasticsearchDomain.DomainArn
                  - /*

  TodoQueryModelUpdater:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/TodoQueryModelUpdater.zip
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSConfigRulesExecutionRole
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - EventsTable
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
      Environment:
        Variables:
          ElasticsearchDomainEndpoint: !GetAtt ElasticsearchDomain.DomainEndpoint
          IotEndpointAddress: !GetAtt IotEndpoint.IotEndpointAddress
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - es:DescribeElasticsearchDomain
                - es:ESHttp*
              Resource: !Join
                - ''
                - - !GetAtt ElasticsearchDomain.DomainArn
                  - /*
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'iot:Connect'
              Resource: '*'
            - Effect: Allow
              Action: 'iot:Publish'
              Resource: !Sub 'arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/todo/*'

  EventsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: aggregateId
          AttributeType: S
        - AttributeName: sequence
          AttributeType: N
      KeySchema:
        - AttributeName: aggregateId
          KeyType: HASH
        - AttributeName: sequence
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - 'Events'

  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - 'search'
      ElasticsearchVersion: '6.3'
      ElasticsearchClusterConfig:
        InstanceCount: '1'
        InstanceType: 't2.small.elasticsearch'
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: 10
        VolumeType: standard
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'

  IotEndpointProvider:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: IotEndpointProvider
      Handler: IotEndpointProvider.handler
      Runtime: nodejs6.10
      CodeUri: .
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - iot:DescribeEndpoint
            Resource:
              - '*'
  IotEndpoint:
    Type: 'Custom::IotEndpoint'
    Properties:
      ServiceToken: !GetAtt IotEndpointProvider.Arn

Outputs:
  ApiRoot:
    Description: "API root"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ElasticsearchDomainEndpoint:
    Description: "Endpoint for Elasticsearch"
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
  IotEndpointAddress:
    Description: "Endpoint for AWS IoT"
    Value: !GetAtt IotEndpoint.IotEndpointAddress
