# see https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Really Hard TODO app
Resources:

  TodoCommand:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/TodoCommand.zip
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 15
      Events:
        Post:
          Type: 'Api'
          Properties:
            Path: '/todo'
            Method: 'post'
      Environment:
        Variables:
          EventsTable: !Ref EventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable

  TodoReadModelUpdater:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/TodoReadModelUpdater.zip
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSConfigRulesExecutionRole
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - EventsTable
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
      Environment:
        Variables:
          EventsTable: !Ref EventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable

  EventsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: aggregateId
          AttributeType: S
        - AttributeName: sequence
          AttributeType: N
      KeySchema:
        - AttributeName: aggregateId
          KeyType: HASH
        - AttributeName: sequence
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName: !Join
        - ''
        - - !Ref 'AWS::StackName'
          - '-Events'

Outputs:
  ApiRoot:
    Description: "API root"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
